version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=Y2Q4MzBhYzktMDI4Ny00M2UyLWEwMjMtZTg4OGNjMWExYWI0
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
    restart: unless-stopped
    volumes:
      - uploads:/app/uploads
      - ./dev.db:/app/dev.db

volumes:
  uploads:
